version: '3.6'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - MONGODB_HOST=db
    command: python -u pgm.py
    ports:
      - "8085:5000"
    secrets:
      - pgm_web_secrets
  db:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - /var/lib/dockervols/pgmdb:/data/db

secrets:
  pgm_web_secrets:
    external: true
