version: '3'
services:
  web:
    image: usgsastro/planetarygeologicmappers
    environment:
      - PYTHONUNBUFFERED=1
    build: .
    command: python -u pgm.py
    ports:
      - "5150:5000"
    links:
      - db
  db:
    image: mongo:3.6.2
    ports:
      - '27017:27017'
    volumes:
      - ./pgmdb:/data/db/
