version: '3.6'
services:
  web:
    image: usgsastro/planetarygeologicmappers:latest
    environment:
      - PYTHONUNBUFFERED=1
      - MONGODB_HOST=db
    command: python -u pgm.py
    ports:
      - "8081:5000"
    secrets:
      - pgm_web_secrets
  db:
    image: mongo:latest
    user: "1555:1555"
    volumes:
      - /var/lib/dockervols/pgm:/data/db

secrets:
  pgm_web_secrets: { external: true }
