---

apiVersion: v1
kind: Namespace
metadata:
  name: planetary-mapping

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pgm-db
  namespace: planetary-mapping
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: pgm
  namespace: planetary-mapping
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pgm
  # Pod template
  template:
    metadata:
      labels:
        app: pgm
    spec:
      containers:
        - name: pgmweb
          image: usgsastro/planetarygeologicmappers:latest
          ports: [{ containerPort: 5000 }]
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            # The two container share a network stack since they're in the
            # same pod, so the mongodb host is localhost
            - name: MONGODB_HOST
              value: "127.0.0.1"
          volumeMounts:
            - name: pgm-secrets
              mountPath: /run/secrets

        - name: pgmdb
          image: mongo:4.2
          volumeMounts:
            - name: vol-pgm-db
              mountPath: /data/db
      volumes:
        - name: pgm-secrets
          secret: { secretName: pgm-web-secrets }
        - name: vol-pgm-db
          persistentVolumeClaim: { claimName: pgm-db }

---

kind: Service
apiVersion: v1
metadata:
  name: pgm
  namespace: planetary-mapping
spec:
  selector:
    app: pgm
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000

---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: pgm
  namespace: planetary-mapping
  labels:
    app: pgm
spec:
  rules:
    - host: planetarymapping.wr.usgs.gov
      http:
        paths:
          - path: /
            backend:
              serviceName: pgm
              servicePort: http

