version: '3.6'
services:
  web:
    image: usgsastro/planetarygeologicmappers
    environment:
      - PYTHONUNBUFFERED=1
      - MONGODB_HOST=db
    command: python -u pgm.py
    ports:
      - "8085:5000"
    secrets:
      - pgm_web_secrets
  db:
    image: mongo:latest
    volumes:
      - vol-pgm:/data/db

volumes:
  vol-pgm: { external: true }

secrets:
  pgm_web_secrets: { external: true }
