version: '3'
services:
  web:
    image: usgsastro/planetarygeologicmappers
    environment:
      - PYTHONUNBUFFERED=1
    build: .
    command: python -u pgm.py
    ports:
      - "8085:5000"
  db:
    image: mongo:3.6.2
    volumes:
      - ./pgmdb:/data/db/
